### PR TITLE
add java support

### PR DESCRIPTION
**Pull request by scottdraves**

### CODE REVIEW

**Comment by scottdraves** [comment]
wait this needs a bit more work...

**Comment by vidartf** [comment]
Feel free to leave it open if you want any input from me while working on it :)

**Comment by scottdraves** [comment]
actually i think it's good.  please let us know your thoughts.
lukasz is working on using it for pythreejs now, so we might find some stuff.

**Comment by vidartf** [comment]
I think the java parser is not needed (writers and parsers are independent of each other). I also see some cleanup I can do in the writer, but there doesn't seem to be anything functionally wrong. As such, I'm just going to merge, and then open another PR here to do cleanup.

**Comment by vidartf** [comment]
PS: I see that you added an APL license to this code. This repo is already licensed under BSD-3 (though I guess I should add an explicit file for that, the only current location is specified in package.json). I'll open up a separate PR where I try to clean this up, and will ping you there if you have any input.

**Comment by scottdraves** [comment]
That was inadvertent, thank you for fixing.

**Pull request merged**
